//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicSQLEntities : DbContext
    {
        public MusicSQLEntities()
            : base("name=MusicSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonné> Abonné { get; set; }
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<Editeur> Editeur { get; set; }
        public virtual DbSet<Emprunter> Emprunter { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
    }
}
